include_guard(GLOBAL)

get_filename_component(NEO_CI_HOST_ROOT "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)

# Invoke programs directly, with argument boundaries intact on every platform.
# Commands and failures are retained in the Actions diagnostics; no shell eval.
function(neo_ci_run)
    cmake_parse_arguments(PARSE_ARGV 0 run "QUIET" "OUTPUT;LOG;WORKING_DIRECTORY;TIMEOUT" "COMMAND")
    if(NOT run_COMMAND OR run_UNPARSED_ARGUMENTS OR run_KEYWORDS_MISSING_VALUES)
        message(FATAL_ERROR "Invalid CI command invocation")
    endif()
    if(NOT run_TIMEOUT)
        set(run_TIMEOUT 1800)
    endif()
    if(NOT run_WORKING_DIRECTORY)
        set(run_WORKING_DIRECTORY "${NEO_CI_HOST_ROOT}")
    endif()
    if(run_LOG)
        get_filename_component(_log_directory "${run_LOG}" DIRECTORY)
        file(MAKE_DIRECTORY "${_log_directory}")
        file(APPEND "${run_LOG}" "\nCommand: ${run_COMMAND}\nDirectory: ${run_WORKING_DIRECTORY}\n")
    endif()
    set(_echo)
    if(NOT run_QUIET)
        message(STATUS "Running: ${run_COMMAND}")
        set(_echo ECHO_OUTPUT_VARIABLE ECHO_ERROR_VARIABLE)
    endif()
    execute_process(COMMAND ${run_COMMAND} WORKING_DIRECTORY "${run_WORKING_DIRECTORY}"
        RESULT_VARIABLE _result OUTPUT_VARIABLE _stdout ERROR_VARIABLE _stderr
        TIMEOUT "${run_TIMEOUT}" ${_echo})
    if(run_LOG)
        file(APPEND "${run_LOG}" "${_stdout}${_stderr}\nExit: ${_result}\n")
    endif()
    if(NOT "${_result}" STREQUAL "0")
        message(FATAL_ERROR "CI command failed (${_result}): ${run_COMMAND}\n${_stdout}${_stderr}")
    endif()
    if(run_OUTPUT)
        set("${run_OUTPUT}" "${_stdout}" PARENT_SCOPE)
    endif()
endfunction()

function(neo_ci_json_string output value)
    string(REPLACE "\\" "\\\\" value "${value}")
    string(REPLACE "\"" "\\\"" value "${value}")
    string(REPLACE "\r" "\\r" value "${value}")
    string(REPLACE "\n" "\\n" value "${value}")
    string(REPLACE "\t" "\\t" value "${value}")
    set("${output}" "\"${value}\"" PARENT_SCOPE)
endfunction()

function(neo_ci_require_sha value length description)
    string(LENGTH "${value}" _length)
    if(NOT _length EQUAL length OR NOT value MATCHES "^[0-9a-fA-F]+$")
        message(FATAL_ERROR "Invalid ${description}: ${value}")
    endif()
endfunction()

function(neo_ci_platform)
    cmake_host_system_information(RESULT _arch QUERY OS_PLATFORM)
    string(TOLOWER "${_arch}" _arch)
    if(CMAKE_HOST_WIN32 AND _arch MATCHES "^(amd64|x86_64|x64)$")
        set(_slug windows-x64)
        set(_generator "Visual Studio 18 2026")
        set(_arch x86_64)
    elseif(CMAKE_HOST_SYSTEM_NAME STREQUAL "Linux" AND _arch MATCHES "^(x86_64|amd64)$")
        set(_slug linux-x64)
        set(_generator Ninja)
        set(_arch x86_64)
    elseif(CMAKE_HOST_APPLE AND _arch MATCHES "^(arm64|aarch64|x86_64)$")
        if(_arch STREQUAL "aarch64")
            set(_arch arm64)
        endif()
        set(_slug "macos-${_arch}")
        set(_generator Ninja)
    else()
        message(FATAL_ERROR "Unconfigured release target: ${CMAKE_HOST_SYSTEM_NAME}/${_arch}")
    endif()
    if(DEFINED ENV{NEOTOOLKIT_EXPECTED_PLATFORM} AND NOT "$ENV{NEOTOOLKIT_EXPECTED_PLATFORM}" STREQUAL ""
       AND NOT "$ENV{NEOTOOLKIT_EXPECTED_PLATFORM}" STREQUAL "${_slug}")
        message(FATAL_ERROR "Runner architecture mismatch: expected $ENV{NEOTOOLKIT_EXPECTED_PLATFORM}, detected ${_slug}")
    endif()
    set(NEO_CI_PLATFORM "${_slug}" PARENT_SCOPE)
    set(NEO_CI_ARCH "${_arch}" PARENT_SCOPE)
    set(NEO_CI_GENERATOR "${_generator}" PARENT_SCOPE)
endfunction()

# Never clean a directory through a link or a junction, or delete a checkout.
# REAL_PATH catches Windows directory junctions as well as ordinary symlinks.
function(neo_ci_no_directory_links directory)
    get_filename_component(_path "${directory}" ABSOLUTE)
    if(_path MATCHES "[;\r\n]")
        message(FATAL_ERROR "Unsupported control/list character in CI path: ${_path}")
    endif()
    while(TRUE)
        if(IS_SYMLINK "${_path}")
            message(FATAL_ERROR "Refusing linked CI directory: ${_path}")
        endif()
        if(EXISTS "${_path}")
            if(NOT IS_DIRECTORY "${_path}")
                message(FATAL_ERROR "Expected a directory: ${_path}")
            endif()
            file(REAL_PATH "${_path}" _real)
            set(_compare "${_path}")
            if(CMAKE_HOST_WIN32)
                string(TOLOWER "${_compare}" _compare)
                string(TOLOWER "${_real}" _real)
            endif()
            if(NOT _compare STREQUAL _real)
                # macOS's /var -> /private/var is a normal system mapping. The
                # caller canonicalizes its base before using this guard.
                message(FATAL_ERROR "CI directory resolves through an alias: ${_path} -> ${_real}")
            endif()
        endif()
        get_filename_component(_parent "${_path}" DIRECTORY)
        if(_parent STREQUAL _path)
            break()
        endif()
        set(_path "${_parent}")
    endwhile()
endfunction()

function(neo_ci_owned_directory output parent name clear)
    if(NOT name MATCHES "^[A-Za-z0-9][A-Za-z0-9._ -]*$")
        message(FATAL_ERROR "Invalid CI directory name: ${name}")
    endif()
    set(_directory "${parent}/${name}")
    neo_ci_no_directory_links("${_directory}")
    if(clear AND EXISTS "${_directory}")
        if(EXISTS "${_directory}/.git" OR EXISTS "${_directory}/CMakeLists.txt")
            message(FATAL_ERROR "Refusing to clear a source directory: ${_directory}")
        endif()
        file(REMOVE_RECURSE "${_directory}")
    endif()
    file(MAKE_DIRECTORY "${_directory}")
    set("${output}" "${_directory}" PARENT_SCOPE)
endfunction()

function(neo_ci_copy source destination)
    get_filename_component(_parent "${destination}" DIRECTORY)
    file(MAKE_DIRECTORY "${_parent}")
    file(COPY_FILE "${source}" "${destination}" ONLY_IF_DIFFERENT)
endfunction()
