cmake_minimum_required(VERSION 3.24)
include("${CMAKE_CURRENT_LIST_DIR}/Common.cmake")
find_package(Git REQUIRED)

if(NOT DEFINED NEO_CI_WORKSPACE)
    get_filename_component(NEO_CI_WORKSPACE "${NEO_CI_HOST_ROOT}/.." ABSOLUTE)
endif()
file(REAL_PATH "${NEO_CI_WORKSPACE}" NEO_CI_WORKSPACE)
neo_ci_no_directory_links("${NEO_CI_WORKSPACE}")
set(_host "${NEO_CI_WORKSPACE}/NeoToolKit-Test")
if(NOT EXISTS "${_host}/CMakeLists.txt")
    message(FATAL_ERROR "The source workspace must contain NeoToolKit-Test/CMakeLists.txt")
endif()
if(NOT DEFINED NEO_CI_MANIFEST)
    set(NEO_CI_MANIFEST "${_host}/ci/components.json")
endif()
file(READ "${NEO_CI_MANIFEST}" _manifest)
string(JSON _schema GET "${_manifest}" schema)
string(JSON _type TYPE "${_manifest}" components)
string(JSON _count LENGTH "${_manifest}" components)
if(NOT _schema EQUAL 1 OR NOT _type STREQUAL "ARRAY" OR _count LESS 1)
    message(FATAL_ERROR "Invalid component manifest")
endif()
set(_log "${NEO_CI_WORKSPACE}/.ci-logs/resolve.log")
file(READ "${_host}/CMakeLists.txt" _cmake)
if(NOT _cmake MATCHES "project\\(NeoToolKitTest[ \r\n\t]+VERSION[ \r\n\t]+([0-9]+\\.[0-9]+\\.[0-9]+)")
    message(FATAL_ERROR "Host version was not found")
endif()
set(_version "${CMAKE_MATCH_1}")
neo_ci_run(COMMAND "${GIT_EXECUTABLE}" -C "${_host}" rev-parse HEAD OUTPUT _host_sha QUIET LOG "${_log}")
string(STRIP "${_host_sha}" _host_sha)
neo_ci_require_sha("${_host_sha}" 40 "host commit")
# The source lock must describe the code actually shipped, not an edited tree.
neo_ci_run(COMMAND "${GIT_EXECUTABLE}" -C "${_host}" status --porcelain --untracked-files=normal
    OUTPUT _dirty QUIET LOG "${_log}")
if(NOT _dirty STREQUAL "")
    message(FATAL_ERROR "Source preparation requires a clean, committed host checkout. No files were reset.\n${_dirty}")
endif()

set(_revision_NeoToolKit-Test "${_host_sha}")
set(_folders NeoToolKit-Test)
set(_keys)
set(_folded_folders neotoolkit-test)
math(EXPR _last "${_count} - 1")
# Validate every destination before fetching anything. Never reset siblings.
foreach(_i RANGE 0 ${_last})
    foreach(_field key folder repository)
        string(JSON _${_field} GET "${_manifest}" components ${_i} ${_field})
    endforeach()
    string(TOLOWER "${_folder}" _folded)
    if(NOT _key MATCHES "^[A-Z][A-Z0-9_]*$" OR NOT _folder MATCHES "^[A-Za-z0-9][A-Za-z0-9_-]*$"
       OR _key IN_LIST _keys OR _folded IN_LIST _folded_folders)
        message(FATAL_ERROR "Invalid or duplicate component: ${_key}/${_folder}")
    endif()
    if(NOT _repository MATCHES "^https://github\\.com/[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$"
       AND NOT _repository MATCHES "^file:///")
        message(FATAL_ERROR "Unsupported component repository: ${_repository}")
    endif()
    if(_repository MATCHES "[;\r\n]")
        message(FATAL_ERROR "Invalid component repository: ${_repository}")
    endif()
    string(JSON _required_type TYPE "${_manifest}" components ${_i} required)
    string(JSON _requirements LENGTH "${_manifest}" components ${_i} required)
    if(NOT _required_type STREQUAL "ARRAY" OR _requirements LESS 1)
        message(FATAL_ERROR "Missing API requirements: ${_folder}")
    endif()
    math(EXPR _r_last "${_requirements} - 1")
    foreach(_r RANGE 0 ${_r_last})
        string(JSON _file GET "${_manifest}" components ${_i} required ${_r} file)
        if(NOT _file MATCHES "^[A-Za-z0-9_./-]+$" OR _file MATCHES "^/|(^|/)\\.\\.(/|$)")
            message(FATAL_ERROR "Unsafe component API path: ${_file}")
        endif()
    endforeach()
    if(EXISTS "${NEO_CI_WORKSPACE}/${_folder}" OR IS_SYMLINK "${NEO_CI_WORKSPACE}/${_folder}")
        message(FATAL_ERROR "Dependency destination already exists: ${NEO_CI_WORKSPACE}/${_folder}. Use a fresh CI workspace; existing sources will not be overwritten.")
    endif()
    list(APPEND _keys "${_key}")
    list(APPEND _folded_folders "${_folded}")
    list(APPEND _folders "${_folder}")
endforeach()
set(_output "${NEO_CI_WORKSPACE}/source-bundle")
if(EXISTS "${_output}" OR IS_SYMLINK "${_output}")
    message(FATAL_ERROR "Source bundle destination already exists: ${_output}. Use a fresh CI workspace.")
endif()
file(MAKE_DIRECTORY "${_output}/.staging")
set(_snapshot "${_output}/.staging")
set(_entries "[]")
set(_summary "")
# Always main: legacy ref variables and dispatch inputs cannot select old APIs.
# Resolve all branches first, then fetch those exact objects for every runner.
foreach(_i RANGE 0 ${_last})
    string(JSON _repository GET "${_manifest}" components ${_i} repository)
    string(JSON _folder GET "${_manifest}" components ${_i} folder)
    neo_ci_run(COMMAND "${GIT_EXECUTABLE}" ls-remote --exit-code "${_repository}" refs/heads/main
        OUTPUT _remote QUIET TIMEOUT 120 LOG "${_log}")
    string(STRIP "${_remote}" _remote)
    if(NOT _remote MATCHES "^([a-fA-F0-9]+)[ \t]+refs/heads/main$")
        message(FATAL_ERROR "Cannot resolve ${_repository} main: ${_remote}")
    endif()
    string(TOLOWER "${CMAKE_MATCH_1}" _commit)
    neo_ci_require_sha("${_commit}" 40 "${_folder} commit")
    set(_commit_${_i} "${_commit}")
    message(STATUS "${_folder}: main -> ${_commit}")
endforeach()
foreach(_i RANGE 0 ${_last})
    foreach(_field key folder repository)
        string(JSON _${_field} GET "${_manifest}" components ${_i} ${_field})
    endforeach()
    set(_commit "${_commit_${_i}}")
    set(_destination "${NEO_CI_WORKSPACE}/${_folder}")
    if(EXISTS "${_destination}" OR IS_SYMLINK "${_destination}")
        message(FATAL_ERROR "Dependency destination appeared during source resolution: ${_destination}. No checkout was overwritten.")
    endif()
    set("_revision_${_folder}" "${_commit}")
    neo_ci_run(COMMAND "${GIT_EXECUTABLE}" init --quiet "${_destination}" QUIET LOG "${_log}")
    neo_ci_run(COMMAND "${GIT_EXECUTABLE}" -C "${_destination}" remote add origin "${_repository}" QUIET LOG "${_log}")
    neo_ci_run(COMMAND "${GIT_EXECUTABLE}" -C "${_destination}" -c core.autocrlf=false fetch --no-tags --depth=1 origin "${_commit}"
        QUIET TIMEOUT 180 LOG "${_log}")
    neo_ci_run(COMMAND "${GIT_EXECUTABLE}" -C "${_destination}" -c core.autocrlf=false checkout --quiet --detach "${_commit}"
        QUIET LOG "${_log}")
    neo_ci_run(COMMAND "${GIT_EXECUTABLE}" -C "${_destination}" rev-parse HEAD OUTPUT _actual QUIET LOG "${_log}")
    neo_ci_run(COMMAND "${GIT_EXECUTABLE}" -C "${_destination}" cat-file -t HEAD OUTPUT _kind QUIET LOG "${_log}")
    string(STRIP "${_actual}" _actual)
    string(STRIP "${_kind}" _kind)
    if(NOT _actual STREQUAL _commit OR NOT _kind STREQUAL "commit")
        message(FATAL_ERROR "Revision verification failed: ${_folder}")
    endif()
    string(JSON _requirements LENGTH "${_manifest}" components ${_i} required)
    math(EXPR _r_last "${_requirements} - 1")
    foreach(_r RANGE 0 ${_r_last})
        string(JSON _file GET "${_manifest}" components ${_i} required ${_r} file)
        set(_api "${_destination}/${_file}")
        set(_matches TRUE)
        if(NOT EXISTS "${_api}" OR IS_DIRECTORY "${_api}")
            set(_matches FALSE)
        else()
            string(JSON _contains ERROR_VARIABLE _error GET "${_manifest}" components ${_i} required ${_r} contains)
            if(NOT _error AND NOT _contains STREQUAL "")
                file(READ "${_api}" _text)
                string(FIND "${_text}" "${_contains}" _position)
                if(_position EQUAL -1)
                    set(_matches FALSE)
                endif()
            endif()
        endif()
        if(NOT _matches)
            message(FATAL_ERROR "${_folder} lacks the workspace API: ${_file}. Publish the complete current source to main. No ref variables are used.")
        endif()
    endforeach()
    set(_entry "{}")
    foreach(_field key folder repository)
        neo_ci_json_string(_value "${_${_field}}")
        string(JSON _entry SET "${_entry}" ${_field} "${_value}")
    endforeach()
    string(JSON _entry SET "${_entry}" requested "\"main\"")
    string(JSON _entry SET "${_entry}" commit "\"${_commit}\"")
    string(JSON _entries SET "${_entries}" ${_i} "${_entry}")
    string(APPEND _summary "| ${_folder} | main | `${_commit}` |\n")
endforeach()
set(_repository "$ENV{GITHUB_REPOSITORY}")
if(_repository STREQUAL "")
    set(_repository "local/NeoToolKit-Test")
endif()
neo_ci_json_string(_repository "${_repository}")
set(_lock "{\"schema\":1,\"version\":\"${_version}\",\"host\":{\"repository\":${_repository},\"commit\":\"${_host_sha}\"},\"components\":${_entries}}")
string(JSON _lock GET "${_lock}")
# Git archives include committed files/modes only, not .git, ignored build
# trees, cached dependencies, credentials, or CI diagnostics.
foreach(_folder IN LISTS _folders)
    set(_tar "${_output}/${_folder}.tar")
    neo_ci_run(COMMAND "${GIT_EXECUTABLE}" -C "${NEO_CI_WORKSPACE}/${_folder}" archive --format=tar
        "--prefix=${_folder}/" "--output=${_tar}" "${_revision_${_folder}}" QUIET LOG "${_log}")
    neo_ci_run(COMMAND "${CMAKE_COMMAND}" -E tar xf "${_tar}" WORKING_DIRECTORY "${_snapshot}" QUIET LOG "${_log}")
    file(REMOVE "${_tar}")
endforeach()
file(WRITE "${_host}/ci-resolved-components.json" "${_lock}\n")
file(WRITE "${_snapshot}/NeoToolKit-Test/ci-resolved-components.json" "${_lock}\n")
file(WRITE "${_output}/component-lock.json" "${_lock}\n")
set(_archive "${_output}/workspace-sources.tar.gz")
neo_ci_run(COMMAND "${CMAKE_COMMAND}" -E tar czf "${_archive}" --format=gnutar ${_folders}
    WORKING_DIRECTORY "${_snapshot}" LOG "${_log}")
file(SHA256 "${_archive}" _digest)
file(WRITE "${_archive}.sha256" "${_digest}  workspace-sources.tar.gz\n")
file(REMOVE_RECURSE "${_snapshot}")
if(NOT "$ENV{GITHUB_OUTPUT}" STREQUAL "")
    file(APPEND "$ENV{GITHUB_OUTPUT}" "source_sha256=${_digest}\nversion=${_version}\nhost_sha=${_host_sha}\n")
endif()
if(NOT "$ENV{GITHUB_STEP_SUMMARY}" STREQUAL "")
    file(APPEND "$ENV{GITHUB_STEP_SUMMARY}" "## Resolved source snapshot\n\nAll four native jobs consume this exact archive.\n\n| Component | Branch | Commit |\n|---|---|---|\n${_summary}\n")
endif()
message(STATUS "Prepared ${_archive}; SHA-256 ${_digest}")
