cmake_minimum_required(VERSION 3.24)
include("${CMAKE_CURRENT_LIST_DIR}/Common.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/VerifyInstall.cmake")
neo_ci_platform()

if(NOT DEFINED NEO_CI_PHASE)
    message(FATAL_ERROR "NEO_CI_PHASE must be configure, build, or package")
endif()
string(TOLOWER "${NEO_CI_PHASE}" NEO_CI_PHASE)
if(NOT NEO_CI_PHASE MATCHES "^(configure|build|package)$")
    message(FATAL_ERROR "NEO_CI_PHASE must be configure, build, or package")
endif()
if(NOT DEFINED NEO_CI_BUILD_DIR OR NEO_CI_BUILD_DIR STREQUAL "")
    set(NEO_CI_BUILD_DIR "${NEO_CI_HOST_ROOT}/build/ci")
endif()
get_filename_component(NEO_CI_BUILD_DIR "${NEO_CI_BUILD_DIR}" ABSOLUTE BASE_DIR "${NEO_CI_HOST_ROOT}")
# Allow macOS system aliases in the source prefix, not links inside the build.
file(REAL_PATH "${NEO_CI_HOST_ROOT}" NEO_CI_HOST_ROOT)
neo_ci_no_directory_links("${NEO_CI_BUILD_DIR}")
cmake_path(IS_PREFIX NEO_CI_BUILD_DIR "${NEO_CI_HOST_ROOT}" NORMALIZE _build_contains_source)
if(_build_contains_source OR EXISTS "${NEO_CI_BUILD_DIR}/CMakeLists.txt" OR EXISTS "${NEO_CI_BUILD_DIR}/.git")
    message(FATAL_ERROR "Refusing to use a source directory as the CI build directory: ${NEO_CI_BUILD_DIR}")
endif()
set(_cache "${NEO_CI_BUILD_DIR}/CMakeCache.txt")
if(EXISTS "${_cache}")
    file(STRINGS "${_cache}" _home REGEX "^CMAKE_HOME_DIRECTORY:INTERNAL=")
    string(REGEX REPLACE "^CMAKE_HOME_DIRECTORY:INTERNAL=" "" _home "${_home}")
    file(REAL_PATH "${_home}" _home)
    if(NOT _home STREQUAL NEO_CI_HOST_ROOT)
        message(FATAL_ERROR "Build cache belongs to another source tree: ${_home}")
    endif()
endif()
file(MAKE_DIRECTORY "${NEO_CI_BUILD_DIR}")
# Prevent concurrent package phases from removing one another's staging files.
file(LOCK "${NEO_CI_BUILD_DIR}/.native-ci.lock" GUARD PROCESS TIMEOUT 0 RESULT_VARIABLE _lock)
if(NOT _lock STREQUAL "0")
    message(FATAL_ERROR "Another CI phase owns ${NEO_CI_BUILD_DIR}: ${_lock}")
endif()
neo_ci_owned_directory(_logs "${NEO_CI_BUILD_DIR}" ci-logs FALSE)

function(neo_ci_record_toolchain)
    cmake_host_system_information(RESULT _release QUERY OS_RELEASE)
    set(_record "{}")
    set(_os "${CMAKE_HOST_SYSTEM_NAME}")
    set(_architecture "${NEO_CI_ARCH}")
    set(_runnerImage "$ENV{ImageOS}")
    set(_runnerImageVersion "$ENV{ImageVersion}")
    neo_ci_run(COMMAND "${CMAKE_COMMAND}" --version OUTPUT _cmake QUIET)
    string(STRIP "${_cmake}" _cmake)
    foreach(_field os architecture release runnerImage runnerImageVersion cmake)
        neo_ci_json_string(_value "${_${_field}}")
        string(JSON _record SET "${_record}" ${_field} "${_value}")
    endforeach()
    string(JSON _record SET "${_record}" vcpkgCommit null)
    if(NOT "$ENV{VCPKG_INSTALLATION_ROOT}" STREQUAL "")
        execute_process(COMMAND git -C "$ENV{VCPKG_INSTALLATION_ROOT}" rev-parse HEAD
            RESULT_VARIABLE _git_result OUTPUT_VARIABLE _commit ERROR_QUIET TIMEOUT 30)
        if(_git_result STREQUAL "0")
            string(STRIP "${_commit}" _commit)
            neo_ci_json_string(_value "${_commit}")
            string(JSON _record SET "${_record}" vcpkgCommit "${_value}")
        endif()
    endif()
    file(WRITE "${_logs}/toolchain.json" "${_record}\n")
    if(EXISTS "${_cache}")
        neo_ci_copy("${_cache}" "${_logs}/CMakeCache.txt")
    endif()
endfunction()

function(neo_ci_read_build)
    set(_metadata "${NEO_CI_BUILD_DIR}/ci-build-Release.json")
    if(NOT EXISTS "${_metadata}")
        message(FATAL_ERROR "Configure the actual workspace GUI first; missing ${_metadata}")
    endif()
    file(READ "${_metadata}" _build)
    foreach(_field version executable sharedRoot platform)
        string(JSON _${_field} GET "${_build}" ${_field})
    endforeach()
    if(NOT _platform STREQUAL NEO_CI_PLATFORM)
        message(FATAL_ERROR "Build platform ${_platform} does not match runner ${NEO_CI_PLATFORM}")
    endif()
    if(NOT _version MATCHES "^[0-9]+\\.[0-9]+\\.[0-9]+$")
        message(FATAL_ERROR "Invalid package version: ${_version}")
    endif()
    if(NOT EXISTS "${_executable}" OR IS_DIRECTORY "${_executable}")
        message(FATAL_ERROR "Build did not produce the workspace executable: ${_executable}")
    endif()
    file(REAL_PATH "${_executable}" _real_executable)
    cmake_path(IS_PREFIX NEO_CI_BUILD_DIR "${_real_executable}" NORMALIZE _inside)
    if(NOT _inside)
        message(FATAL_ERROR "Workspace executable is outside its build directory: ${_executable}")
    endif()
    foreach(_field version executable sharedRoot platform)
        set("NEO_CI_BUILD_${_field}" "${_${_field}}" PARENT_SCOPE)
    endforeach()
endfunction()

if(NEO_CI_PHASE STREQUAL "configure")
    set(_args -S "${NEO_CI_HOST_ROOT}" -B "${NEO_CI_BUILD_DIR}" -G "${NEO_CI_GENERATOR}"
        -DCMAKE_BUILD_TYPE=Release -DNEOTOOLKIT_BUILD_GUI=ON
        -DNEOTOOLKIT_BUILD_STANDALONES=OFF -DNEOTOOLKIT_USE_SIBLINGS=ON -DBUILD_SHARED_LIBS=OFF)
    if(CMAKE_HOST_WIN32)
        if(NOT DEFINED NEO_CI_VCPKG_ROOT OR NEO_CI_VCPKG_ROOT STREQUAL "")
            set(NEO_CI_VCPKG_ROOT "$ENV{VCPKG_INSTALLATION_ROOT}")
        endif()
        file(TO_CMAKE_PATH "${NEO_CI_VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake" _toolchain)
        if(NOT EXISTS "${_toolchain}")
            message(FATAL_ERROR "Runner vcpkg toolchain is unavailable: ${_toolchain}")
        endif()
        list(APPEND _args -A x64 "-DCMAKE_TOOLCHAIN_FILE=${_toolchain}"
            -DVCPKG_TARGET_TRIPLET=x64-windows-static -DVCPKG_MANIFEST_MODE=OFF
            "-DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded$<$<CONFIG:Debug>:Debug>")
    elseif(CMAKE_HOST_APPLE)
        neo_ci_run(COMMAND brew --prefix wxwidgets OUTPUT _prefix QUIET LOG "${_logs}/configure.log")
        string(STRIP "${_prefix}" _prefix)
        if(NOT EXISTS "${_prefix}/bin/wx-config")
            message(FATAL_ERROR "Homebrew wxWidgets SDK is unavailable: ${_prefix}")
        endif()
        list(APPEND _args "-DCMAKE_OSX_ARCHITECTURES=${NEO_CI_ARCH}"
            -DCMAKE_OSX_DEPLOYMENT_TARGET=15.0 "-DwxWidgets_CONFIG_EXECUTABLE=${_prefix}/bin/wx-config")
    endif()
    neo_ci_record_toolchain()
    neo_ci_run(COMMAND "${CMAKE_COMMAND}" ${_args} LOG "${_logs}/configure.log")
    neo_ci_record_toolchain()
elseif(NEO_CI_PHASE STREQUAL "build")
    set(_jobs "$ENV{NEOTOOLKIT_BUILD_JOBS}")
    if(_jobs STREQUAL "")
        set(_jobs 2)
    endif()
    if(NOT _jobs MATCHES "^[1-9][0-9]*$")
        message(FATAL_ERROR "NEOTOOLKIT_BUILD_JOBS must be a positive integer")
    endif()
    neo_ci_run(COMMAND "${CMAKE_COMMAND}" --build "${NEO_CI_BUILD_DIR}" --config Release --parallel "${_jobs}"
        LOG "${_logs}/build.log" TIMEOUT 7200)
    neo_ci_read_build()
else()
    neo_ci_read_build()
    neo_ci_record_toolchain()
    neo_ci_owned_directory(_stage "${NEO_CI_BUILD_DIR}" stage-workspace TRUE)
    neo_ci_owned_directory(_dist "${NEO_CI_BUILD_DIR}" dist TRUE)
    neo_ci_run(COMMAND "${CMAKE_COMMAND}" --install "${NEO_CI_BUILD_DIR}" --config Release
        --prefix "${_stage}" --component toolkit-runtime LOG "${_logs}/install.log")
    neo_ci_inspect_stage("${_stage}" _installed_executable)
    if(CMAKE_HOST_APPLE)
        neo_ci_run(COMMAND bash "${NEO_CI_BUILD_sharedRoot}/scripts/package-macos-app.sh"
            --app "${_stage}/NeoToolKit-Test.app"
            --output "${_dist}/NeoToolKit-Test-${NEO_CI_BUILD_version}-${NEO_CI_PLATFORM}.zip"
            --arch "${NEO_CI_ARCH}" --app-name "NeoToolKit Test" --version "${NEO_CI_BUILD_version}"
            --deployment-target 15.0 LOG "${_logs}/macos-bundle.log")
    else()
        if(CMAKE_HOST_WIN32)
            set(_generators ZIP)
        else()
            set(_generators TGZ DEB)
        endif()
        foreach(_generator IN LISTS _generators)
            neo_ci_run(COMMAND "${CMAKE_CPACK_COMMAND}" --config "${NEO_CI_BUILD_DIR}/CPackConfig.cmake"
                -C Release -G "${_generator}" -B "${_dist}"
                WORKING_DIRECTORY "${NEO_CI_BUILD_DIR}" LOG "${_logs}/cpack-${_generator}.log")
        endforeach()
    endif()
    file(GLOB _packages RELATIVE "${_dist}" "${_dist}/*.zip" "${_dist}/*.tar.gz" "${_dist}/*.deb")
    list(SORT _packages)
    list(LENGTH _packages _count)
    set(_expected 1)
    if(CMAKE_HOST_SYSTEM_NAME STREQUAL "Linux")
        set(_expected 2)
    endif()
    if(NOT _count EQUAL _expected)
        message(FATAL_ERROR "Expected ${_expected} distribution files; found ${_count}")
    endif()
    set(_results "[]")
    set(_summary "")
    set(_index 0)
    foreach(_package IN LISTS _packages)
        set(_file "${_dist}/${_package}")
        neo_ci_owned_directory(_unpack "${NEO_CI_BUILD_DIR}" "installed package ${_index}" TRUE)
        if(_package MATCHES "\\.deb$")
            neo_ci_run(COMMAND dpkg-deb --field "${_file}" OUTPUT _meta LOG "${_logs}/deb-metadata.log")
            if(NOT _meta MATCHES "(^|\n)Depends:[ \t]*[^ \t\r\n]")
                message(FATAL_ERROR "DEB has no computed runtime dependency list")
            endif()
            neo_ci_run(COMMAND dpkg-deb --extract "${_file}" "${_unpack}" LOG "${_logs}/deb-extract.log")
            set(_installed "${_unpack}/usr")
        else()
            if(CMAKE_HOST_APPLE)
                neo_ci_run(COMMAND ditto -x -k "${_file}" "${_unpack}" LOG "${_logs}/archive-extract.log")
                set(_installed "${_unpack}")
            else()
                neo_ci_run(COMMAND "${CMAKE_COMMAND}" -E tar xf "${_file}" WORKING_DIRECTORY "${_unpack}"
                    LOG "${_logs}/archive-extract.log")
                set(_installed "${_unpack}/NeoToolKit-Test-${NEO_CI_BUILD_version}-${NEO_CI_PLATFORM}")
            endif()
        endif()
        neo_ci_verify_install("${_installed}" "${_logs}/installed-${_index}")
        file(SHA256 "${_file}" _digest)
        file(SIZE "${_file}" _size)
        file(WRITE "${_file}.sha256" "${_digest}  ${_package}\n")
        neo_ci_json_string(_name "${_package}")
        string(JSON _results SET "${_results}" ${_index}
            "{\"file\":${_name},\"sha256\":\"${_digest}\",\"size\":${_size},\"packageChecks\":\"passed\"}")
        string(APPEND _summary "- ${_package} (${_size} bytes), SHA-256 `${_digest}`\n")
        math(EXPR _index "${_index} + 1")
    endforeach()
    if(EXISTS "${NEO_CI_HOST_ROOT}/ci-resolved-components.json")
        neo_ci_copy("${NEO_CI_HOST_ROOT}/ci-resolved-components.json" "${_dist}/component-lock.json")
    endif()
    neo_ci_copy("${_logs}/toolchain.json" "${_dist}/toolchain.json")
    if(CMAKE_HOST_APPLE)
        set(_signing "ad-hoc; not notarized")
    elseif(CMAKE_HOST_WIN32)
        set(_signing unsigned)
    else()
        set(_signing "not applicable")
    endif()
    neo_ci_json_string(_signing "${_signing}")
    set(_metadata "{\"version\":\"${NEO_CI_BUILD_version}\",\"platform\":\"${NEO_CI_PLATFORM}\",\"packages\":${_results},\"signing\":${_signing}}")
    string(JSON _metadata GET "${_metadata}")
    file(WRITE "${_dist}/packages.json" "${_metadata}\n")
    if(NOT "$ENV{GITHUB_STEP_SUMMARY}" STREQUAL "")
        file(APPEND "$ENV{GITHUB_STEP_SUMMARY}" "## ${NEO_CI_PLATFORM} packages\n\nBuild and package checks passed.\n\n${_summary}\n")
    endif()
endif()
