cmake_minimum_required(VERSION 3.24)
include("${CMAKE_CURRENT_LIST_DIR}/Common.cmake")

function(neo_ci_inspect_stage root output)
    if(CMAKE_HOST_APPLE)
        set(_relative "NeoToolKit-Test.app/Contents/MacOS/NeoToolKit-Test")
    elseif(CMAKE_HOST_WIN32)
        set(_relative "bin/NeoToolKit-Test.exe")
    else()
        set(_relative "bin/NeoToolKit-Test")
    endif()
    set(_exe "${root}/${_relative}")
    if(NOT EXISTS "${_exe}" OR IS_DIRECTORY "${_exe}")
        message(FATAL_ERROR "Installed workspace executable is missing: ${_exe}")
    endif()
    file(SIZE "${_exe}" _size)
    if(_size EQUAL 0)
        message(FATAL_ERROR "Installed workspace executable is empty: ${_exe}")
    endif()
    if(NOT CMAKE_HOST_WIN32)
        neo_ci_run(COMMAND test -x "${_exe}" QUIET)
    endif()
    file(REAL_PATH "${root}" _root_real)
    get_filename_component(_exe_directory "${_exe}" DIRECTORY)
    file(GLOB_RECURSE _files LIST_DIRECTORIES TRUE "${root}/*")
    foreach(_file IN LISTS _files)
        file(RELATIVE_PATH _relative "${root}" "${_file}")
        if(_relative MATCHES "(^|/)(CMakeCache\\.txt|CMakeFiles|\\.git)(/|$)")
            message(FATAL_ERROR "Build or source state leaked into package: ${_file}")
        endif()
        if(IS_SYMLINK "${_file}" AND NOT EXISTS "${_file}")
            message(FATAL_ERROR "Broken link in package: ${_file}")
        endif()
        file(REAL_PATH "${_file}" _real)
        cmake_path(IS_PREFIX _root_real "${_real}" NORMALIZE _contained)
        if(NOT _contained)
            message(FATAL_ERROR "Package entry points outside its installation: ${_file}")
        endif()
        if(IS_DIRECTORY "${_file}")
            continue()
        endif()
        get_filename_component(_parent "${_file}" DIRECTORY)
        string(TOLOWER "${_file}" _lower)
        if(_parent STREQUAL _exe_directory AND NOT _file STREQUAL _exe)
            if(NOT CMAKE_HOST_WIN32 OR NOT _lower MATCHES "\\.dll$")
                message(FATAL_ERROR "Unexpected executable-directory member: ${_file}")
            endif()
        endif()
    endforeach()
    if(CMAKE_HOST_APPLE)
        if(NOT EXISTS "${root}/NeoToolKit-Test.app/Contents/Info.plist")
            message(FATAL_ERROR "Bundle Info.plist is missing")
        endif()
        file(GLOB _bundles "${root}/*.app")
        list(LENGTH _bundles _bundles_count)
        if(NOT _bundles_count EQUAL 1)
            message(FATAL_ERROR "Standalone app bundles leaked into workspace package")
        endif()
    endif()
    set("${output}" "${_exe}" PARENT_SCOPE)
endfunction()

function(neo_ci_windows_dependencies exe logs)
    set(_program_files "$ENV{ProgramFiles\(x86\)}")
    if(_program_files STREQUAL "")
        set(_program_files "C:/Program Files (x86)")
    endif()
    set(_vswhere "${_program_files}/Microsoft Visual Studio/Installer/vswhere.exe")
    if(NOT EXISTS "${_vswhere}")
        message(FATAL_ERROR "Cannot locate vswhere for the installed-package dependency check")
    endif()
    neo_ci_run(COMMAND "${_vswhere}" -latest -products "*"
        -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64
        -find "VC/Tools/MSVC/*/bin/Hostx64/x64/dumpbin.exe"
        OUTPUT _tools QUIET LOG "${logs}/installed-dependencies.log")
    string(REPLACE "\r" "" _tools "${_tools}")
    string(STRIP "${_tools}" _tools)
    string(REPLACE "\n" ";" _tools "${_tools}")
    list(FILTER _tools EXCLUDE REGEX "^$")
    if(NOT _tools)
        message(FATAL_ERROR "Cannot locate dumpbin for the installed-package dependency check")
    endif()
    list(SORT _tools COMPARE NATURAL)
    list(GET _tools -1 _dumpbin)
    neo_ci_run(COMMAND "${_dumpbin}" /NOLOGO /DEPENDENTS "${exe}"
        OUTPUT _imports LOG "${logs}/installed-dependencies.log")
    string(REPLACE "\r" "" _imports "${_imports}")
    string(REPLACE "\n" ";" _lines "${_imports}")
    set(_names)
    foreach(_line IN LISTS _lines)
        string(STRIP "${_line}" _line)
        string(TOLOWER "${_line}" _lower)
        if(_lower MATCHES "^[a-z0-9_.+-]+\\.dll$")
            list(APPEND _names "${_line}")
        endif()
    endforeach()
    list(REMOVE_DUPLICATES _names)
    if(NOT _names)
        message(FATAL_ERROR "dumpbin returned no import inventory")
    endif()
    set(_system "$ENV{SystemRoot}")
    if(_system STREQUAL "")
        set(_system "C:/Windows")
    endif()
    foreach(_name IN LISTS _names)
        string(TOLOWER "${_name}" _lower)
        if(_lower MATCHES "^(msvcp|vcruntime|concrt)[0-9]")
            message(FATAL_ERROR "Unexpected redistributable DLL with the static CRT build: ${_name}")
        endif()
        if(_lower MATCHES "^(api-ms-|ext-ms-)")
            continue()
        endif()
        if(NOT EXISTS "${_system}/System32/${_name}")
            message(FATAL_ERROR "Unbundled non-system dependency: ${_name}")
        endif()
    endforeach()
endfunction()

function(neo_ci_verify_install root logs)
    neo_ci_inspect_stage("${root}" _exe)
    file(MAKE_DIRECTORY "${logs}")
    if(CMAKE_HOST_SYSTEM_NAME STREQUAL "Linux")
        neo_ci_run(COMMAND ldd "${_exe}" OUTPUT _deps LOG "${logs}/installed-dependencies.log")
        if(_deps MATCHES "not found")
            message(FATAL_ERROR "Installed Linux executable has unresolved dependencies")
        endif()
    elseif(CMAKE_HOST_WIN32)
        neo_ci_windows_dependencies("${_exe}" "${logs}")
    elseif(CMAKE_HOST_APPLE)
        neo_ci_run(COMMAND codesign --verify --deep --strict --verbose=2 "${root}/NeoToolKit-Test.app"
            LOG "${logs}/installed-signatures.log")
    else()
        message(FATAL_ERROR "No installed-package check for ${CMAKE_HOST_SYSTEM_NAME}")
    endif()
endfunction()

if(CMAKE_SCRIPT_MODE_FILE STREQUAL CMAKE_CURRENT_LIST_FILE)
    if(NOT DEFINED NEO_CI_STAGE OR NOT DEFINED NEO_CI_LOGS)
        message(FATAL_ERROR "NEO_CI_STAGE and NEO_CI_LOGS are required")
    endif()
    neo_ci_verify_install("${NEO_CI_STAGE}" "${NEO_CI_LOGS}")
endif()
